name: PROD System

on:
  push:
    branches:
      - main
    paths-ignore:
      - "services/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install Angular CLI
        run: npm install -g @angular/cli

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build:prod
      
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-prod
          path: dist

  deploy:
    runs-on: [prod]
    needs: build
    steps:
      - name: Create necessary directories if they don't exist
        run: |
          mkdir -p /home/sites/backup/system
          mkdir -p /home/sites/system

      - name: Delete old backup
        run: rm -rf /home/sites/backup/system/*

      - name: Backup current files
        run: cp -r /home/sites/system/. /home/sites/backup/system/

      - name: Clean system
        run: rm -rf /home/sites/system/*

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: build-prod
          path: /home/sites/system/

